

export interface ITheme {
  span_text_size_s: string | number,
  span_text_size_m: string | number,
  span_text_size_l: string | number,
  span_text_line_height_s: string | number,
  span_text_line_height_m: string | number,
  span_text_line_height_l: string | number,

  h1_text_line_height_s: string | number,
  h1_text_line_height_m: string | number,
  h1_text_line_height_l: string | number,
  h2_text_line_height_s: string | number,
  h2_text_line_height_m: string | number,
  h2_text_line_height_l: string | number,
  h3_text_line_height_s: string | number,
  h3_text_line_height_m: string | number,
  h3_text_line_height_l: string | number,
  h4_text_line_height_s: string | number,
  h4_text_line_height_m: string | number,
  h4_text_line_height_l: string | number,
  h5_text_line_height_s: string | number,
  h5_text_line_height_m: string | number,
  h5_text_line_height_l: string | number,
  h6_text_line_height_s: string | number,
  h6_text_line_height_m: string | number,
  h6_text_line_height_l: string | number,

  h1_text_size_s: string | number,
  h1_text_size_m: string | number,
  h1_text_size_l: string | number,
  h2_text_size_s: string | number,
  h2_text_size_m: string | number,
  h2_text_size_l: string | number,
  h3_text_size_s: string | number,
  h3_text_size_m: string | number,
  h3_text_size_l: string | number,
  h4_text_size_s: string | number,
  h4_text_size_m: string | number,
  h4_text_size_l: string | number,
  h5_text_size_s: string | number,
  h5_text_size_m: string | number,
  h5_text_size_l: string | number,
  h6_text_size_s: string | number,
  h6_text_size_m: string | number,
  h6_text_size_l: string | number,
  text_color_default: string,
  text_color_secondary: string,
}
export const global_theme: ITheme = {
  span_text_size_s: 12,
  span_text_size_m: 16,
  span_text_size_l: 20,
  span_text_line_height_s: '1.2',
  span_text_line_height_m: '1.2',
  span_text_line_height_l: '1.2',
  text_color_default: "rgb(64, 69, 78)",
  text_color_secondary: "rgb(163, 163, 163)",
  h1_text_size_s: "",
  h1_text_size_m: "",
  h1_text_size_l: "",
  h2_text_size_s: "",
  h2_text_size_m: "",
  h2_text_size_l: "",
  h3_text_size_s: "",
  h3_text_size_m: "",
  h3_text_size_l: "",
  h4_text_size_s: "",
  h4_text_size_m: "",
  h4_text_size_l: "",
  h5_text_size_s: "",
  h5_text_size_m: "",
  h5_text_size_l: "",
  h6_text_size_s: "",
  h6_text_size_m: "",
  h6_text_size_l: "",
  h1_text_line_height_s: "",
  h1_text_line_height_m: "",
  h1_text_line_height_l: "",
  h2_text_line_height_s: "",
  h2_text_line_height_m: "",
  h2_text_line_height_l: "",
  h3_text_line_height_s: "",
  h3_text_line_height_m: "",
  h3_text_line_height_l: "",
  h4_text_line_height_s: "",
  h4_text_line_height_m: "",
  h4_text_line_height_l: "",
  h5_text_line_height_s: "",
  h5_text_line_height_m: "",
  h5_text_line_height_l: "",
  h6_text_line_height_s: "",
  h6_text_line_height_m: "",
  h6_text_line_height_l: ""
}


